### ISSUE TITLE
Add support for asset paths that start with tilda

### ISSUE THREAD

**Issue by kilwo** [speier/mvcassetshelper#6]
Hello,
  The render function should support paths that start with a ~ to keep in line with the default behavior in MVC.  The following section can be updated in the Render function to support this.

`foreach (var item in _items)`
`{`
`var fmt = string.Format(_format, (item.StartsWith("~", StringComparison.OrdinalIgnoreCase) ? VirtualPathUtility.ToAbsolute(item) : item));`
`sb.AppendLine(fmt);`
`}`

Cheers,
Kilwo

**Comment by speier** [comment]
willing to add this feature in the asp.net core port of this library, see:
https://github.com/speier/mvcassetshelper/tree/aspnetcore
